name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.12.26

    steps:
    - uses: actions/checkout@v2
    - name: Terraform Format 
      run: |
              terraform fmt -check -recursive -diff
              
      env:
          MODULE_ORG : admin
          MODULE_NAME : workspace-factory-gcp
          MODULE_VERSION : 1.0.0
    # - name: PAcklo 
    #   run: |
    #           terraform fmt -check -recursive -diff
    #           tar --exclude-vcs-ignores --exclude-vcs -zcvf module.tar.gz *
    #           echo $GIT_COMMIT_SHORT
    #           ls
    #   env:
    #       MODULE_ORG : admin
    #       MODULE_NAME : workspace-factory-gcp
    #       MODULE_VERSION : 1.0.0
  pack:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: PAcklo 
      run: |
              terraform fmt -check -recursive -diff
              tar --exclude-vcs-ignores --exclude-vcs -zcvf module.tar.gz *
              echo $GIT_COMMIT_SHORT
              ls
      env:
          MODULE_ORG : admin
          MODULE_NAME : workspace-factory-gcp
          MODULE_VERSION : 1.0.0          
