name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.12.26

    steps:
    - uses: actions/checkout@v2
    - name: Hello 
      run: |
              terraform fmt -check -recursive -diff
              tar -zcvf module.tar.gz *
              echo $GIT_COMMIT_SHORT
              ls
      env:
          MODULE_ORG : admin
          MODULE_NAME : workspace-factory-gcp
          MODULE_VERSION : 1.0.0
    
            
      


